 apiVersion: v1
 kind: Service
 metadata:
   name: mcode-service
 spec:
   type: NodePort
   selector:
     app: mcode-service
   ports:
   - protocol: "TCP"
     port: 80
     targetPort: 8000
#   type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcode-service
spec:
  selector:
    matchLabels:
      app: mcode-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mcode-service
    spec:
      containers:
      - name: mcode-service
        image: docker.io/ligulfzhou53/mcode-service
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: "postgresql://root:POSTGRESzlg153@postgresql.default.svc.cluster.local/mcode"
        ports:
        - containerPort: 8000
